### PR TITLE
add  emitGVCF  Default

### PR DESCRIPTION
**Pull request by xubo245**
add  emitGVCF : add  emitGVCF  Default

### CODE REVIEW

**Comment by xubo245** [comment]
Why?

**Comment by fnothaft** [comment]
Hi @xubo245! My apologies about not taking the change. I completed a major refactor in #198 that rewrites most of the core datastructures and algorithms.

**Comment by xubo245** [comment]
Thank you. When do you release a new version？please

**Comment by fnothaft** [comment]
I'm hoping to get a release out towards the end of this month.

**Comment by xubo245** [comment]
Thanks, I will try new function later.

**Pull request closed without merging**
