### PR TITLE
[avocado-122] Tested and reintegrated EM algorithm.

### LINKED ISSUE #122: Re-integrate EM algorithm for calculating genotype state priors
This was removed during re-packaging a few months back (believe in #96).

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #122. Reintegrated EM algorithm for estimating frequency of reference allele, which is used as a prior when genotyping.

### CODE REVIEW

**Comment by fnothaft** [comment]
This now depends on #129.

**Comment by tdanford** [comment]
@fnothaft Can you rebase this?

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
With the switch to log probabilities in #134 to fix #133, I just rewrote this to use all log probabilities in the EM loop as well. So, this now depends on #134, which depends in turn on #130.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by tdanford** [comment]
Is this rebased, @fnothaft ?

**Comment by tdanford** [comment]
@fnothaft I'm going to be offline for about 2 hours, will merge this (LGTM!) when I come back if you've rebased.

**Comment by fnothaft** [comment]
@tdanford rebased!

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by tdanford** [comment]
@fnothaft ... thanks!

**Pull request merged**
